### ISSUE TITLE
Create training dataset for ML Model 

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/CouncilML#4]
## Context
We are working on building a ML Model to power two new functionality on Engage.town:
* Search bar
* Topic Categorization

## File(s)
File will need to be created in with the below format

|Subject/Title |Recommanded Actions | Executive Summary |
|-------------|:----------------------:|:--------------------:|
|                      |                                       |                                   |
|                      |                                       |                                   |
|                      |                                       |                                   |

## Tasks
- [ ] Collect data from 2016-2019 using current scrapper
- [ ] Create custom scrapper to get data from 2010-2015
- [ ] Run scrapper and load data into an .csv file

**Comment by TeddyCr** [comment]
Data already available in CouncilML [repo](https://github.com/hackla-engage/CouncilML)
