### ISSUE TITLE
Train ML Model for Agenda Meeting Meta Data

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/CouncilML#5]
## Context
We are working on building a ML pipeline to power new functionality on engage.town:
* Automatic Topic Categorization
This issue relates to the development of ML algorithm

## File
TBD

## Tasks
- [ ] Read over contents and see notebook at: https://github.com/ylou/CouncilML/tree/master/doc_embedder
- [ ] Contact @eselkin for reference on ML models and research already completed
- [ ] Download JSONs with labeled data for years of agenda items here.
- [ ] If you need a refresher on embeddings, see [this google post](https://developers.google.com/machine-learning/crash-course/embeddings/obtaining-embeddings)

**Comment by eselkin** [comment]
Search should not be contained in ML and should be a simple Elasticsearch on the contents and tags.
Also, it's not a model, since we are doing NLP using fasttext. It should be a pipeline.

**Comment by TeddyCr** [comment]
Thanks specifying Eli. :)

**Comment by owenjoseph** [comment]
@TeddyCr @eselkin should this be closed?

**Comment by owenjoseph** [comment]
Moving to "future development" for now.
